create table produto
(
    id                 integer generated by default as identity
        primary key,
    categoria          smallint
        constraint produto_categoria_check
            check ((categoria >= 0) AND (categoria <= 6)),
    cor                varchar(255),
    descricao          varchar(255),
    imagem             bytea,
    nome               varchar(255),
    preco              double precision,
    quantidade         integer,
    quantidade_estoque integer,
    tamanho            integer
);