spring:
  security:
    user:
      name: well
      password: 123
  docker:
    compose:
      enabled: false
  application:
    name: ecoomerce
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://129.148.16.186:5498/microservices_usuarios
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"

server:
  port: 1001
springdoc:
  show-actuator: true
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
    url: /api-docs